create table social_data (
	username VARCHAR(50),
	full_name VARCHAR(50),
	birthdate DATE,
	location VARCHAR(11),
	bio TEXT,
	followers_count INT,
	following_count INT,
	profile_pic VARCHAR(50),
	status VARCHAR(9),
	join_date DATE
);
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('aruger0', 'Angelia Ruger', '8/6/1992', 'Miami', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 473393, 937, 'https://robohash.org/voluptatequivoluptatem.png?size=50x50&set=set1', 'Active', '8/4/2011');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('blandman1', 'Burtie Landman', '2/11/1966', 'Chicago', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 280813, 381, 'https://robohash.org/etnisivoluptas.png?size=50x50&set=set1', 'Active', '10/10/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('plieber2', 'Pearline Lieber', '4/14/2001', 'Los Angeles', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 990855, 881, 'https://robohash.org/possimustemporaunde.png?size=50x50&set=set1', 'Suspended', '8/29/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('dbaybutt3', 'Dorelle Baybutt', '11/23/1990', 'Los Angeles', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 883087, 727, 'https://robohash.org/voluptatibusaccusantiumet.png?size=50x50&set=set1', 'Active', '6/11/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lcossons4', 'Llewellyn Cossons', '4/4/1996', 'Chicago', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 604327, 17, 'https://robohash.org/illobeataevoluptatem.png?size=50x50&set=set1', 'Active', '10/14/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('farmour5', 'Forrester Armour', '12/8/1967', 'Los Angeles', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 914450, 904, 'https://robohash.org/ipsaquaeperspiciatis.png?size=50x50&set=set1', 'Suspended', '12/30/2011');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('sdorey6', 'Sonny Dorey', '1/26/1956', 'New York', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 19254, 864, 'https://robohash.org/exquihic.png?size=50x50&set=set1', 'Inactive', '7/4/2014');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('aklimkovich7', 'Adrian Klimkovich', '9/9/1993', 'Chicago', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 489606, 348, 'https://robohash.org/minuslaudantiumplaceat.png?size=50x50&set=set1', 'Suspended', '7/25/2016');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('tharesnaip8', 'Town Haresnaip', '6/16/1963', 'Chicago', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 32308, 66, 'https://robohash.org/expeditanihiltotam.png?size=50x50&set=set1', 'Inactive', '2/27/2012');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('kgenicke9', 'Kennett Genicke', '1/22/1955', 'New York', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 846163, 20, 'https://robohash.org/etquiavoluptatem.png?size=50x50&set=set1', 'Active', '1/1/2018');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('amccowana', 'Ann-marie McCowan', '2/12/1971', 'Miami', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 183874, 645, 'https://robohash.org/evenietutnesciunt.png?size=50x50&set=set1', 'Active', '11/19/2021');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('rdamarellb', 'Ram Damarell', '6/23/1975', 'Chicago', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 382374, 439, 'https://robohash.org/autemipsaquisquam.png?size=50x50&set=set1', 'Suspended', '2/8/2015');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lpietznerc', 'Lowell Pietzner', '12/17/1998', 'Miami', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 236820, 753, 'https://robohash.org/nonabalias.png?size=50x50&set=set1', 'Inactive', '10/12/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('btolcharded', 'Barbabas Tolcharde', '1/27/1996', 'Los Angeles', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 360768, 393, 'https://robohash.org/quibusdamrepellataliquid.png?size=50x50&set=set1', 'Inactive', '11/23/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('qmowlame', 'Quent Mowlam', '4/19/1957', 'Chicago', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 3639, 896, 'https://robohash.org/estlaudantiumalias.png?size=50x50&set=set1', 'Suspended', '4/23/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('jpiattif', 'Jarvis Piatti', '3/19/1987', 'New York', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 57119, 282, 'https://robohash.org/corruptiiustodelectus.png?size=50x50&set=set1', 'Suspended', '5/28/2013');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('bkynving', 'Bronnie Kynvin', '7/12/1958', 'Chicago', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 775862, 172, 'https://robohash.org/aliquamquosasperiores.png?size=50x50&set=set1', 'Active', '8/20/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('efallonh', 'Emory Fallon', '9/23/1968', 'Miami', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 671762, 442, 'https://robohash.org/sinttemporibusquia.png?size=50x50&set=set1', 'Suspended', '3/8/2012');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('cpayi', 'Cordelia Pay', '6/1/1965', 'New York', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 271984, 976, 'https://robohash.org/accusamussedassumenda.png?size=50x50&set=set1', 'Active', '7/1/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('kbinesj', 'Ken Bines', '2/20/1952', 'Miami', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 668854, 282, 'https://robohash.org/consecteturatquereprehenderit.png?size=50x50&set=set1', 'Active', '6/13/2013');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('pstiellk', 'Peder Stiell', '7/18/1955', 'Chicago', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 637322, 648, 'https://robohash.org/ipsaetquidem.png?size=50x50&set=set1', 'Inactive', '8/26/2018');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('ehowiesonl', 'Elnora Howieson', '5/12/1983', 'Miami', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 73479, 319, 'https://robohash.org/doloremdignissimosmagni.png?size=50x50&set=set1', 'Suspended', '4/3/2012');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('eveldem', 'Ellen Velde', '1/17/1985', 'Miami', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 462326, 791, 'https://robohash.org/velitofficiismolestias.png?size=50x50&set=set1', 'Active', '7/25/2015');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('tforthn', 'Tulley Forth', '11/18/1990', 'Miami', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 416428, 215, 'https://robohash.org/enimquiablanditiis.png?size=50x50&set=set1', 'Active', '9/28/2011');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('jdiveso', 'Jecho Dives', '8/8/1996', 'Miami', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 459939, 266, 'https://robohash.org/eaetexpedita.png?size=50x50&set=set1', 'Active', '8/31/2021');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('rkensettp', 'Raquel Kensett', '10/5/1991', 'Los Angeles', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 660544, 858, 'https://robohash.org/eligendiexercitationemadipisci.png?size=50x50&set=set1', 'Inactive', '6/21/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('elyptrattq', 'Estrella Lyptratt', '7/13/1970', 'New York', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 404678, 499, 'https://robohash.org/eosetnobis.png?size=50x50&set=set1', 'Suspended', '2/2/2012');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('mwithinshawr', 'Mervin Withinshaw', '1/24/2000', 'Miami', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 289122, 227, 'https://robohash.org/numquamaniminostrum.png?size=50x50&set=set1', 'Inactive', '1/23/2013');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('jchetters', 'Janine Chetter', '7/22/1967', 'Miami', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 304621, 589, 'https://robohash.org/sedculpatenetur.png?size=50x50&set=set1', 'Active', '2/2/2014');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('yblazewskit', 'Yettie Blazewski', '5/23/1983', 'Los Angeles', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 153007, 476, 'https://robohash.org/dolorumcorruptiillum.png?size=50x50&set=set1', 'Active', '8/11/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('dterbruggeu', 'Donn Terbrugge', '2/28/1971', 'Los Angeles', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.

Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 477373, 594, 'https://robohash.org/consequunturvoluptatumquidem.png?size=50x50&set=set1', 'Suspended', '8/3/2014');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('bcamockv', 'Bonnibelle Camock', '10/21/2000', 'Chicago', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 769663, 429, 'https://robohash.org/quamvitaeexcepturi.png?size=50x50&set=set1', 'Active', '2/20/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lkiftw', 'Leonidas Kift', '7/18/1989', 'Miami', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 922739, 62, 'https://robohash.org/voluptaslaudantiumarchitecto.png?size=50x50&set=set1', 'Inactive', '12/14/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('dfairburnx', 'Danie Fairburn', '8/9/2001', 'Chicago', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 33133, 943, 'https://robohash.org/sedidaspernatur.png?size=50x50&set=set1', 'Active', '4/21/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('bseresy', 'Britte Seres', '7/21/1958', 'Los Angeles', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 455342, 34, 'https://robohash.org/etautemsed.png?size=50x50&set=set1', 'Active', '7/18/2016');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lwickmannz', 'Leyla Wickmann', '5/15/1987', 'Chicago', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 427129, 414, 'https://robohash.org/nullaametsit.png?size=50x50&set=set1', 'Inactive', '2/13/2014');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('foade10', 'Fanny Oade', '5/11/1979', 'Los Angeles', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 945417, 286, 'https://robohash.org/cumquereprehenderitrerum.png?size=50x50&set=set1', 'Inactive', '1/3/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('bjerrard11', 'Benedetto Jerrard', '3/8/1955', 'Los Angeles', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 531918, 963, 'https://robohash.org/providenteiusquia.png?size=50x50&set=set1', 'Active', '12/17/2016');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('upretor12', 'Uriah Pretor', '2/6/1959', 'New York', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 61064, 989, 'https://robohash.org/inautemvoluptatem.png?size=50x50&set=set1', 'Active', '12/10/2016');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('bvolkers13', 'Briny Volkers', '5/24/1983', 'Chicago', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 976468, 746, 'https://robohash.org/teneturnumquampraesentium.png?size=50x50&set=set1', 'Suspended', '1/6/2014');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('acorbet14', 'Aliza Corbet', '5/28/1959', 'Chicago', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 354084, 500, 'https://robohash.org/temporapariaturmagnam.png?size=50x50&set=set1', 'Suspended', '9/28/2018');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('tmccullum15', 'Tiffie McCullum', '2/25/1985', 'New York', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 682316, 889, 'https://robohash.org/minusipsamet.png?size=50x50&set=set1', 'Active', '6/18/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('sbeesley16', 'Shirl Beesley', '1/21/1966', 'New York', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 823270, 959, 'https://robohash.org/magnamvoluptatemdolor.png?size=50x50&set=set1', 'Active', '4/11/2014');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('kdaouse17', 'Karlene Daouse', '10/15/1967', 'Miami', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 715612, 935, 'https://robohash.org/blanditiisdolorescommodi.png?size=50x50&set=set1', 'Active', '9/27/2013');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('kkybert18', 'Kristin Kybert', '5/24/1957', 'Miami', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 807283, 338, 'https://robohash.org/quodsedquia.png?size=50x50&set=set1', 'Inactive', '7/1/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('mayers19', 'Mandie Ayers', '1/1/1990', 'New York', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 983928, 61, 'https://robohash.org/harummodilaborum.png?size=50x50&set=set1', 'Suspended', '6/15/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('dfaier1a', 'Dyna Faier', '12/3/1969', 'New York', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 141391, 767, 'https://robohash.org/laboreexpeditaautem.png?size=50x50&set=set1', 'Suspended', '4/17/2010');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('ipaszek1b', 'Immanuel Paszek', '2/17/1954', 'New York', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 377292, 115, 'https://robohash.org/nesciuntnemosoluta.png?size=50x50&set=set1', 'Inactive', '10/12/2018');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('rseverns1c', 'Renato Severns', '9/30/1964', 'Miami', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 228369, 135, 'https://robohash.org/istealiasanimi.png?size=50x50&set=set1', 'Inactive', '4/11/2018');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('mmacalister1d', 'Mariejeanne MacAlister', '7/28/1973', 'Chicago', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 402602, 754, 'https://robohash.org/molestiasvoluptassit.png?size=50x50&set=set1', 'Suspended', '4/30/2014');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('mhigginbottam1e', 'Mirella Higginbottam', '5/1/1999', 'New York', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 103298, 273, 'https://robohash.org/rerumnamquibusdam.png?size=50x50&set=set1', 'Inactive', '4/9/2013');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('slivingstone1f', 'Skipp Livingstone', '7/21/1985', 'New York', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 511194, 32, 'https://robohash.org/idsapienteunde.png?size=50x50&set=set1', 'Suspended', '6/9/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('mfannin1g', 'Marleah Fannin', '1/2/1987', 'New York', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 592068, 900, 'https://robohash.org/sedevenietsapiente.png?size=50x50&set=set1', 'Suspended', '8/9/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('pgillam1h', 'Phaidra Gillam', '3/5/1967', 'Chicago', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 404707, 106, 'https://robohash.org/sedoditamet.png?size=50x50&set=set1', 'Suspended', '6/6/2011');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('sdibb1i', 'Sher Dibb', '12/28/1954', 'New York', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 367919, 74, 'https://robohash.org/liberoeosqui.png?size=50x50&set=set1', 'Inactive', '2/11/2021');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('isetterington1j', 'Israel Setterington', '2/21/1999', 'Los Angeles', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 266704, 969, 'https://robohash.org/sedullamillo.png?size=50x50&set=set1', 'Suspended', '11/15/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lnials1k', 'Lammond Nials', '8/31/1975', 'New York', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 437424, 5, 'https://robohash.org/doloremsaepesunt.png?size=50x50&set=set1', 'Inactive', '4/5/2010');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('adussy1l', 'Asia Dussy', '7/5/1975', 'Miami', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 894192, 469, 'https://robohash.org/aliquamliberoofficia.png?size=50x50&set=set1', 'Suspended', '11/13/2016');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('jnegro1m', 'Jonell Negro', '4/30/1966', 'Miami', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 79936, 985, 'https://robohash.org/dolorumesseunde.png?size=50x50&set=set1', 'Active', '6/8/2013');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('sjaeggi1n', 'Sydelle Jaeggi', '5/9/1956', 'Los Angeles', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 80904, 571, 'https://robohash.org/consecteturdolorsequi.png?size=50x50&set=set1', 'Suspended', '9/26/2011');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('csmallpeace1o', 'Celinda Smallpeace', '2/16/1995', 'Los Angeles', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 318189, 902, 'https://robohash.org/etquiavoluptatem.png?size=50x50&set=set1', 'Active', '3/22/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('mbalogh1p', 'Michal Balogh', '9/10/1976', 'Los Angeles', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 475187, 245, 'https://robohash.org/etpariaturerror.png?size=50x50&set=set1', 'Inactive', '7/25/2010');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('vtippler1q', 'Vanda Tippler', '10/22/1972', 'New York', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 264759, 23, 'https://robohash.org/consequunturmollitiasimilique.png?size=50x50&set=set1', 'Inactive', '5/25/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lfolbige1r', 'Lorettalorna Folbige', '4/13/1958', 'Chicago', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 775555, 612, 'https://robohash.org/quoblanditiiset.png?size=50x50&set=set1', 'Active', '6/17/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('slindman1s', 'Scotty Lindman', '3/30/1993', 'New York', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 592167, 499, 'https://robohash.org/etreprehenderittempore.png?size=50x50&set=set1', 'Inactive', '10/13/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('dsorrie1t', 'Dannye Sorrie', '11/6/1962', 'Los Angeles', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 232882, 274, 'https://robohash.org/assumendasintqui.png?size=50x50&set=set1', 'Active', '11/14/2010');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lleivers1u', 'Lion Leivers', '6/4/1964', 'Chicago', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 337509, 232, 'https://robohash.org/dolorabet.png?size=50x50&set=set1', 'Suspended', '12/7/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('asilveston1v', 'Ania Silveston', '11/29/1980', 'Los Angeles', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 193393, 824, 'https://robohash.org/quoeteum.png?size=50x50&set=set1', 'Inactive', '12/14/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('brickert1w', 'Barnabe Rickert', '4/3/1954', 'Miami', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 487767, 47, 'https://robohash.org/etdeseruntexercitationem.png?size=50x50&set=set1', 'Inactive', '7/13/2018');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('jhuntingford1x', 'Joscelin Huntingford', '3/22/1996', 'Los Angeles', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 629469, 785, 'https://robohash.org/uteosaliquam.png?size=50x50&set=set1', 'Inactive', '1/31/2015');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('vlemonnier1y', 'Valaree Lemonnier', '8/25/1996', 'Los Angeles', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 344034, 800, 'https://robohash.org/quidemveritatisquia.png?size=50x50&set=set1', 'Active', '5/3/2010');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('cbanasevich1z', 'Chaddy Banasevich', '3/11/1986', 'Miami', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 480174, 641, 'https://robohash.org/etrepellendusnam.png?size=50x50&set=set1', 'Suspended', '5/29/2021');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('keble20', 'Kristofor Eble', '11/26/1975', 'Miami', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 908773, 707, 'https://robohash.org/voluptatemabmollitia.png?size=50x50&set=set1', 'Active', '6/12/2021');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lphilbrook21', 'Lamond Philbrook', '12/18/1982', 'Chicago', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 204401, 146, 'https://robohash.org/aliasveronesciunt.png?size=50x50&set=set1', 'Active', '5/27/2012');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('shaulkham22', 'Sidney Haulkham', '3/15/1999', 'Chicago', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 613775, 234, 'https://robohash.org/remcorporistempora.png?size=50x50&set=set1', 'Active', '4/27/2018');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('dtwell23', 'Danyelle Twell', '6/8/1995', 'Chicago', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 891900, 225, 'https://robohash.org/commodivellaudantium.png?size=50x50&set=set1', 'Suspended', '3/22/2021');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('ybeden24', 'Yvonne Beden', '8/10/2002', 'Los Angeles', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 135022, 4, 'https://robohash.org/repellendusconsequunturamet.png?size=50x50&set=set1', 'Active', '1/24/2015');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('cblastock25', 'Carena Blastock', '10/28/1979', 'Chicago', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 995897, 868, 'https://robohash.org/inventoredolortenetur.png?size=50x50&set=set1', 'Inactive', '5/5/2011');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('stickner26', 'Sophi Tickner', '3/5/1985', 'Miami', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 738086, 982, 'https://robohash.org/sequiexercitationemperferendis.png?size=50x50&set=set1', 'Active', '7/28/2015');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('cmcalinden27', 'Cchaddie McAlinden', '4/6/1990', 'New York', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 837224, 740, 'https://robohash.org/etdolorumvoluptate.png?size=50x50&set=set1', 'Inactive', '7/15/2021');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('wattenburrow28', 'Wallache Attenburrow', '8/10/1973', 'Miami', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 954568, 883, 'https://robohash.org/perspiciatissimiliquenecessitatibus.png?size=50x50&set=set1', 'Inactive', '5/11/2016');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('ebernardt29', 'Edmund Bernardt', '7/17/1960', 'New York', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 546771, 258, 'https://robohash.org/accusantiumodiodolorum.png?size=50x50&set=set1', 'Suspended', '6/6/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('rferie2a', 'Renata Ferie', '9/20/1993', 'New York', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 777469, 451, 'https://robohash.org/doloribusmagniperspiciatis.png?size=50x50&set=set1', 'Inactive', '4/4/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('ocristou2b', 'Olive Cristou', '12/7/1979', 'Miami', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 699736, 529, 'https://robohash.org/voluptasperspiciatismaxime.png?size=50x50&set=set1', 'Inactive', '2/26/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('hveale2c', 'Halsy Veale', '12/18/1983', 'Los Angeles', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 37699, 226, 'https://robohash.org/quiaetpossimus.png?size=50x50&set=set1', 'Suspended', '12/6/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('nkighly2d', 'Ninnetta Kighly', '9/23/1956', 'Los Angeles', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 248204, 827, 'https://robohash.org/quisquamidmollitia.png?size=50x50&set=set1', 'Inactive', '12/19/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('zabramzon2e', 'Zora Abramzon', '2/9/1993', 'Los Angeles', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 253528, 704, 'https://robohash.org/velitsedvoluptas.png?size=50x50&set=set1', 'Active', '8/5/2016');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('mcure2f', 'Martyn Cure', '5/15/1971', 'New York', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 813986, 420, 'https://robohash.org/abvelrepellendus.png?size=50x50&set=set1', 'Inactive', '7/5/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('rwhicher2g', 'Robenia Whicher', '11/10/1952', 'Los Angeles', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 456220, 693, 'https://robohash.org/sapienteinet.png?size=50x50&set=set1', 'Inactive', '6/19/2013');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('chodcroft2h', 'Cathleen Hodcroft', '7/1/2002', 'Chicago', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 533245, 265, 'https://robohash.org/repellatestvoluptas.png?size=50x50&set=set1', 'Active', '7/24/2017');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lgroocock2i', 'Loella Groocock', '8/11/1954', 'Miami', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 462737, 256, 'https://robohash.org/molestiaesuntautem.png?size=50x50&set=set1', 'Suspended', '1/28/2012');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('cgroucutt2j', 'Chrissy Groucutt', '5/17/2002', 'New York', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 417027, 319, 'https://robohash.org/sitoccaecatialiquid.png?size=50x50&set=set1', 'Inactive', '4/29/2014');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('dcolqueran2k', 'Dreddy Colqueran', '9/10/1964', 'Los Angeles', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 509767, 374, 'https://robohash.org/voluptasquisminus.png?size=50x50&set=set1', 'Active', '5/6/2010');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('climb2l', 'Claudianus Limb', '1/17/1984', 'Los Angeles', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.

Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 661175, 216, 'https://robohash.org/earumeummagni.png?size=50x50&set=set1', 'Inactive', '10/17/2018');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('bmaurice2m', 'Bryce Maurice', '12/9/1957', 'New York', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 787637, 54, 'https://robohash.org/rerumetdolores.png?size=50x50&set=set1', 'Suspended', '11/15/2019');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('bdix2n', 'Beltran Dix', '10/5/1989', 'Miami', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 380370, 714, 'https://robohash.org/commodisimiliqueest.png?size=50x50&set=set1', 'Active', '3/13/2015');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('rlennon2o', 'Roanne Lennon', '9/28/1979', 'Los Angeles', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 784571, 243, 'https://robohash.org/dolorescupiditatetotam.png?size=50x50&set=set1', 'Active', '10/27/2020');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('lkinch2p', 'Lura Kinch', '5/29/1967', 'Chicago', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 835686, 93, 'https://robohash.org/sinteiusquidem.png?size=50x50&set=set1', 'Suspended', '9/23/2011');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('mworsley2q', 'Millicent Worsley', '9/6/1955', 'Chicago', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 334404, 210, 'https://robohash.org/abquasiet.png?size=50x50&set=set1', 'Suspended', '1/22/2012');
insert into social_data (username, full_name, birthdate, location, bio, followers_count, following_count, profile_pic, status, join_date) values ('mitzakovitz2r', 'Marcelia Itzakovitz', '11/27/1968', 'New York', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 876081, 159, 'https://robohash.org/quaeratquiserror.png?size=50x50&set=set1', 'Inactive', '6/16/2021');
